Repository gnembon/scarpet, pull requests merged in 2021-06, with the labels that each got.

#213 Add new scripts to survival category
  programs/survival/item_holding_mobs_despawn_rule.sc
  programs/survival/show_bees_count.sc
  programs/survival/showbiome.sc
Labels: new-app

#216 Fixed a few bugs, implemented afew features
  programs/survival/waypoints.sc
Labels: app-update

#222 add silk touch budding amethyst script
  programs/survival/README.md
  programs/survival/silk_budding_amethyst.sc
Labels: new-app

#220 add lava_sponge.sc
  programs/survival/README.md
  programs/survival/lava_sponge.sc
Labels: new-app

#225 Adding hyperlinks to apps in the readmes
  programs/survival/README.md
Labels: documentation, enhancement
