Repository gnembon/scarpet, pull requests merged in 2021-07, with the labels that each got.

#231 deprecated nether tick in nether_poi.sc
  programs/survival/nether_poi.sc
Labels: app-update

#205 Added bucketstack.sc survival script and description
  programs/survival/README.md
  programs/survival/bucketstack.sc
Labels: new-app

#228 Update resource_app.sc
  programs/tutorial/resource_app.sc
Labels: refactor, tech-debt
