Repository gnembon/scarpet, pull requests merged in 2021-03, with the labels that each got.

#188 Update camera.sc compared to Fabric Carpet (alternative to #187)
  programs/utilities/camera.sc
Labels: app-update

#189 Upgrade deprecated usages in storage drawers
  programs/survival/storage_drawers.sc
Labels: app-update, tech-debt

#196 Add flower forest flowers script
  programs/utilities/flower.sc
Labels: new-app
