Repository gnembon/scarpet, pull requests merged in 2021-12, with the labels that each got.

#266 fix carried_totem.sc "false alarm" issues, new pr
  programs/survival/carried_totem.sc
Labels: bug

#252 Skip night
  programs/survival/README.md
  skip_night.sc
Labels: new-app

#235 Add portalorient script
  programs/survival/README.md
  programs/survival/portalorient.sc
Labels: new-app

#249 Fixes #248 by checking for matching potion effect when item was potion
  programs/survival/shulkerboxes.sc
Labels: app-update

#177 Add new scripts
  programs/libraries/README.md
  programs/libraries/pretty_print.sc
  programs/survival/README.md
  programs/survival/bee_healing.sc
  programs/survival/compass.sc
  programs/survival/shoot_fireball.sc
Labels: new-app

#221 Update Cam: Actionbar instead of chat, simplify and fix timeout
  programs/survival/cam.sc
Labels: app-update

#276 Fix for case where force-gamemode is on
  programs/survival/cam.sc
Labels: app-update

#269 No Useless Llamas - New App
  programs/survival/README.md
  programs/survival/no_useless_llamas.sc
Labels: new-app

#272 Rename shapes.sc to sshapes.sc
  programs/building/sshapes.sc
Labels: app-update, tech-debt
