Repository gnembon/scarpet, pull requests merged in 2022-02, with the labels that each got.

#262 Updated and improved flower.sc
  programs/utilities/flower.sc
Labels: app-update

#286 Add instamine deepslate script
  programs/survival/README.md
  programs/survival/instamine_deepslate.sc
Labels: new-app

#295 Fix `gm.sc` comment mentioning survival twice
  programs/utilities/gm.sc
Labels: app-update, documentation

#294 Add a link to programs in the README
  README.md
Labels: documentation
