Repository gnembon/scarpet, pull requests merged in 2022-10, with the labels that each got.

#344 Add sound to eye remover
  programs/survival/eyeremover.sc
Labels: enhancement, app-update

#293 Add geode projection app
  programs/utilities/geode_projection.sc
Labels: new-app

#342 Fix typo in `cover.sc`
  programs/building/cover.sc
Labels: documentation

#314 Preserving players flying state when reloading in keepalive.sc
  programs/utilities/keepalive.sc
Labels: app-update
